include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/presentation/paint/**

  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    avoid_classes_with_only_static_members: ignore
    sort_pub_dependencies: ignore
    constant_identifier_names: ignore
